# Build environment
FROM node:15.13-alpine as build 
WORKDIR /frontend 
ENV PATH="./node_modules/.bin:$PATH"
COPY package.json ./
COPY yarn.lock ./
RUN yarn install 
COPY . .
RUN yarn run build

# Production environment
FROM nginx:stable-alpine 
COPY --from=build /frontend/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]