# Generated by Django 3.2.3 on 2021-05-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField()),
                ('reset_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Par',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=10)),
                ('current_par_qty', models.IntegerField()),
                ('recommended_par_qty', models.IntegerField()),
                ('review_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('members', models.ManyToManyField(through='reset.Membership', to='reset.Par')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reset.par'),
        ),
        migrations.AddField(
            model_name='membership',
            name='reset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reset.reset'),
        ),
    ]
