# Generated by Django 3.2.3 on 2021-05-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField()),
                ('reset_level', models.IntegerField()),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reset.par')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('changes', models.ManyToManyField(through='reset.Change', to='reset.Par')),
            ],
        ),
        migrations.RemoveField(
            model_name='reset',
            name='members',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Reset',
        ),
        migrations.AddField(
            model_name='change',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reset.submission'),
        ),
    ]
