# Generated by Django 3.2.3 on 2021-05-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0002_auto_20210526_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Change',
            new_name='Reset',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='changes',
        ),
        migrations.AddField(
            model_name='submission',
            name='resets',
            field=models.ManyToManyField(through='reset.Reset', to='reset.Par'),
        ),
    ]
