# Generated by Django 3.2.3 on 2021-05-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0003_auto_20210526_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reset',
            new_name='Itemreset',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='resets',
        ),
        migrations.AddField(
            model_name='submission',
            name='itemresets',
            field=models.ManyToManyField(through='reset.Itemreset', to='reset.Par'),
        ),
    ]
