# Generated by Django 3.2.3 on 2021-05-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0004_auto_20210526_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='month',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
