# Generated by Django 3.2.3 on 2021-06-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0005_submission_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='par',
            name='dept_id',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='description',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='expense_account_no',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='ext_delta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='imms',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='location_id',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='location_name',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='qty_delta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='unit_cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='uom',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='uom_conv_factor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='par',
            name='wt_avg_cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
