# Generated by Django 3.2.3 on 2021-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0006_auto_20210610_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='par',
            name='ext_delta',
            field=models.FloatField(),
        ),
    ]
