# Generated by Django 3.2.3 on 2021-06-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0007_alter_par_ext_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
