# Generated by Django 3.2.3 on 2021-06-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0008_alter_submission_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreset',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
