# Generated by Django 3.2.3 on 2021-06-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0009_alter_itemreset_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='itemresets',
        ),
    ]
