# Generated by Django 3.2.3 on 2021-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0010_remove_submission_itemresets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreset',
            name='submission',
        ),
        migrations.AddField(
            model_name='itemreset',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemreset',
            name='week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemreset',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
