# Generated by Django 3.2.3 on 2021-06-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0011_auto_20210614_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
