# Generated by Django 3.2.3 on 2021-06-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0013_itemreset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='par',
            name='mfr',
            field=models.CharField(default='Medline', max_length=250),
        ),
    ]
