# Generated by Django 3.2.3 on 2021-06-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0014_par_mfr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemreset',
            options={'ordering': ['-week']},
        ),
        migrations.AlterModelOptions(
            name='par',
            options={'ordering': ['-review_date', '-ext_delta', 'id']},
        ),
        migrations.AlterField(
            model_name='itemreset',
            name='par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemresets', to='reset.par', unique=True),
        ),
    ]
