# Generated by Django 3.2.3 on 2021-06-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0015_auto_20210622_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemreset',
            options={'ordering': ['-week', 'id']},
        ),
        migrations.AlterField(
            model_name='itemreset',
            name='par',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itemresets', to='reset.par'),
        ),
    ]
