# Generated by Django 3.2.3 on 2021-06-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0016_auto_20210625_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
