# Generated by Django 3.2.3 on 2021-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0019_auto_20210705_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreset',
            name='send_back_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='par',
            name='mfr',
            field=models.CharField(default='default', max_length=250),
        ),
    ]
