apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 8000
  selector:
    app: backend
