version: "3"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    volumes:
      - ./backend/:/backend/
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/frontend/
    ports:
      - 3000:3000
    container_name: react_updated
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword 
      - POSTGRES_DB=plr
    ports:
      - 5433:5432


volumes:
  postgres_data:
        