apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: gcr.io/testplr/frontend
        name: react-updated
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /frontend/
            name: frontend
        args:
          - "yarn start"
    volumes:
      - name: frontend
        hostPath:
          path: /frontend/
