# Generated by Django 3.2.3 on 2021-07-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='is_flag',
            field=models.CharField(default='Yes', max_length=3),
        ),
    ]
