# Generated by Django 3.2.3 on 2021-07-30 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reset', '0020_auto_20210707_1748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0003_flag_is_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_shipping', to='reset.itemreset')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
