# Generated by Django 3.2.3 on 2021-07-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='reset',
        ),
        migrations.AddField(
            model_name='shipping',
            name='facility_code',
            field=models.CharField(default='def', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
