# Generated by Django 3.2.3 on 2021-08-03 00:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20210730_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='reset_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, null=True, size=None),
        ),
    ]
