# Generated by Django 3.2.3 on 2021-06-25 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
