# Generated by Django 3.2.3 on 2021-07-05 22:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
