# Generated by Django 3.2.3 on 2021-08-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_iam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iam',
            field=models.CharField(blank=True, choices=[('satx_acute', 'satx_acute'), ('satx_dc', 'satx_dc'), ('resolute', 'resolute'), ('west_acute', 'west_acute')], default='satx_acute', max_length=50),
        ),
    ]
